package com.xiagao.mapper;

import com.xiagao.model.pojo.mybatis.GroupPermissionEntity;
import java.util.List;

public interface GroupPermissionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int insert(GroupPermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    GroupPermissionEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    List<GroupPermissionEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int updateByPrimaryKey(GroupPermissionEntity record);
}