package com.xiagao.mapper;

import com.xiagao.model.pojo.mybatis.GroupRoleEntity;
import java.util.List;

public interface GroupRoleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int insert(GroupRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    GroupRoleEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    List<GroupRoleEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_role
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int updateByPrimaryKey(GroupRoleEntity record);
}