package com.xiagao.mapper;

import com.xiagao.model.pojo.mybatis.LogEntity;
import java.util.List;

public interface LogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int insert(LogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    LogEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    List<LogEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int updateByPrimaryKey(LogEntity record);
}