package com.xiagao.mapper;

import com.xiagao.model.pojo.mybatis.OrganizationEntity;
import java.util.List;

public interface OrganizationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int insert(OrganizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    OrganizationEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    List<OrganizationEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int updateByPrimaryKey(OrganizationEntity record);
}