package com.xiagao.mapper;

import com.xiagao.model.pojo.mybatis.UserPermissionEntity;
import java.util.List;

public interface UserPermissionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int insert(UserPermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    UserPermissionEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    List<UserPermissionEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int updateByPrimaryKey(UserPermissionEntity record);
}