package com.xiagao.mapper;

import com.xiagao.model.pojo.mybatis.UserGroupEntity;
import java.util.List;

public interface UserGroupEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int insert(UserGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    UserGroupEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    List<UserGroupEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_group
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    int updateByPrimaryKey(UserGroupEntity record);
}