package com.xiagao.model.pojo.mybatis;

import java.io.Serializable;

public class OrganizationEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.id
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.name
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.create_time
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.description
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.parent_id
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_organization
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.id
     *
     * @return the value of t_organization.id
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.id
     *
     * @param id the value for t_organization.id
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.name
     *
     * @return the value of t_organization.name
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.name
     *
     * @param name the value for t_organization.name
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.create_time
     *
     * @return the value of t_organization.create_time
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.create_time
     *
     * @param createTime the value for t_organization.create_time
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.description
     *
     * @return the value of t_organization.description
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.description
     *
     * @param description the value for t_organization.description
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.parent_id
     *
     * @return the value of t_organization.parent_id
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.parent_id
     *
     * @param parentId the value for t_organization.parent_id
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Thu Jul 02 16:31:03 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", createTime=").append(createTime);
        sb.append(", description=").append(description);
        sb.append(", parentId=").append(parentId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}